# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ym-test-nbdev',
                'doc_host': 'https://maiyishan.github.io',
                'git_url': 'https://github.com/maiyishan/ym-test-nbdev',
                'lib_path': 'ym_test_nbdev'},
  'syms': {'ym_test_nbdev.core': {'ym_test_nbdev.core.foo': ('core.html#foo', 'ym_test_nbdev/core.py')}}}