# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/00_core.ipynb 3
suits = ("Diamond", "Hearts", "Clubs", "Spades")
ranks = [None, "A"] + [str(x) for x in range(2,11)] + ["J", "Q", "K"]

# %% ../nbs/00_core.ipynb 7
class Card:
    
    ## This creates a line in documentation; you can preview by using the show_doc command. Splitting up the __init__ into rows creates a table: see below
    "A playing card."
    
    ##initialization of the object
    def __init__(self, 
                 suit:int, #Indexes from `suit` 
                 rank:int): #Indexes from `ranks`
        self.suit = suits[suit]
        self.rank = ranks[rank]
        
    ## dunder str: how to string-ify your object
    def __str__(self):return self.rank + " of " + self.suit
    
    ## causes Jupyter to output the str. version when the object itself is called; reproduces into the notebook
    __repr__ = __str__
